trigger:
- master

pool:
  name: default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
- script: |
    sudo apt install nodejs
  displayName: 'Install Node.js'

- script: |
    touch /tmp/koodi1 /tmp/naveen1
  displayName: 'creating files'


  
