trigger:
- master

pool:
  name: default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    touch /tmp/koodi /tmp/naveen 
  displayName: 'npm install'


  
